export const listings = [
  {
    id: "cat-307e2-2016",
    title: "2016 CATERPILLAR 307E2",
    category: "Amphibious Excavator",
    location: "Houston, Texas",
    hours: 737,
    monthly: "USD $30,000",
    priceText: "CALL FOR PRICE",
    images: [
      "/2016Cterpillar1.jpeg",
      "/2016Cterpillar2.jpeg",
      "/2016Cterpillar3.jpeg",
      "/2016Cterpillar4.jpeg",
      "/2016Cterpillar5.jpeg",
      "/2016Cterpillar6.jpeg",
      "/2016Cterpillar7.jpeg",
      "/2016Cterpillar8.jpeg",
      "/2016Cterpillar9.jpeg",
      "/2016Cterpillar10.jpeg",
    ],
    featured: true,
    specs: {
      year: 2016,
      manufacturer: "CATERPILLAR",
      model: "307E2",
      serialNumber: "KC900365",
      condition: "Used",
      hours: 737,
    },
    description:
      `2016 CAT307E2 Amphibious Excavator / Marsh Buggy\nKC900365\n-737 Machine Hours\n-0 Hours on EIK AM80 Amphibious Undercarriage\n-0 Hours on EIK Boom, EIK Stick and EIK Bucket\n-30' EIK Long Reach Boom and Stick\n-40" EIK Ditching bucket\n-Aux hydraulics W steel lines to the stick\n-Hydraulically Extendable and Retractable Undercarriage\n-Window Tint\n-35k lbs\n-Pontoons retract to 11' 6" for over the road travel\n\nWE DO NOT NEED TRUCKING SERVICES`,
    attachments: {
      "Number of Buckets": "1",
      "Bucket Width": "40 in",
    },
    categorySpecific: {
      "Operating Weight": "35,000 lb",
      "Auxiliary Hydraulics": "Yes",
      Thumb: "Yes",
      "Arm Length": "30 ft",
      "Reach Type": "Long / Super Long",
      "Boom Type": "2-Piece",
      "Boom Length": "30 ft",
    },
    chassis: {
      "Track Type": "Steel",
      Counterweight: "Yes",
      Amphibious: "Yes",
    },
    interior: {
      "A/C": "Yes",
      "A/C Condition": "Excellent",
      Heater: "Yes",
    },
    shipping: {
      "Shipping Width": "11 ft 1 in",
      "Shipping Weight": "35,000 lb",
    },
    machineLocation: "111 Houston, Texas 77001",
    seller: {
      name: "O'Shea Equipment Company",
      contact: "Shamus O'Shea",
      phone: "(817) 422-1393",
      city: "Montgomery, Texas 77356-3219",
    },
  },
  {
    id: "cat-312e-2014",
    title: "2014 CATERPILLAR 312E",
    category: "Amphibious Excavator",
    location: "Houston, Texas",
    hours: 1361,
    monthly: "USD $30,000",
    priceText: "CALL FOR PRICE",
    images: [
      "/2014Cterpillar1.jpeg",
      "/2014Cterpillar2.jpeg",
      "/2014Cterpillar3.jpeg",
      "/2014Cterpillar4.jpeg",
      "/2014Cterpillar5.jpeg",
      "/2014Cterpillar6.jpeg",
      "/2014Cterpillar7.jpeg",
    ],
    featured: true,
    specs: {
      year: 2014,
      manufacturer: "CATERPILLAR",
      model: "312E",
      serialNumber: "PZL00717",
      condition: "Used",
      hours: 1361,
      hoursMeter: "Accurate / Verified",
    },
    description:
      `2014 CAT312E Amphibious Excavator / Marsh Buggy\nPZL00717\n-1,361 Machine Hours\n-41 Hours on EIK AM140 Amphibious Undercarriage\n-41 Hours on EIK Boom, EIK Stick and EIK Bucket\n-40' EIK Long Reach Boom and Stick\n-40" EIK Ditching bucket\n-Aux hydraulics\n-Hydraulically Extendable and Retractable Undercarriage\n-55k lbs\n-Pontoons retract to 11' 6" for over the road travel\n\nWE DO NOT NEED TRUCKING SERVICES`,
    attachments: {
      "Number of Buckets": "1",
      "Bucket Width": "40 in",
    },
    categorySpecific: {
      "Auxiliary Hydraulics": "Yes",
      "Arm Length": "40 ft",
      "Reach Type": "Long / Super Long",
    },
    chassis: {
      "Track Type": "Steel",
      Counterweight: "Yes",
      Amphibious: "Yes",
    },
    interior: {
      "A/C": "Yes",
      "A/C Condition": "Excellent",
      Heater: "Yes",
    },
    shipping: {
      "Shipping Width": "11 ft 6 in",
      "Shipping Weight": "55,000 lb",
    },
    machineLocation: "111 Houston, Texas 77001",
    seller: {
      name: "O'Shea Equipment Company",
      contact: "Shamus O'Shea",
      phone: "(817) 422-1393",
      city: "Montgomery, Texas 77356-3219",
    },
  },
  {
    id: "cat-330-2022",
    title: "2022 CATERPILLAR 330",
    category: "Amphibious Excavator",
    location: "Houston, Texas",
    hours: 1043,
    monthly: "USD $50,000",
    priceText: "CALL FOR PRICE",
    images: [
      "/2022Cterpillar1.jpeg",
      "/2022Cterpillar2.webp",
      "/2022Cterpillar3.jpeg",
      "/2022Cterpillar4.jpeg",
      "/2022Cterpillar5.jpeg",
      "/2022Cterpillar6.jpeg",
      "/2022Cterpillar7.jpeg",

    ],
    featured: true,
    specs: {
      year: 2022,
      manufacturer: "CATERPILLAR",
      model: "330",
      serialNumber: "XNB20096",
      condition: "Used",
      hours: 1043,
    },
    description:
      `2022 CAT330 Amphibious Excavator / Marsh Buggy\nXNB20096\n-1,043 Machine Hours Very Clean machine\n-0 Hours on EIK AM300 Amphibious Undercarriage\n-0 Hours on EIK Boom, EIK Stick and 60" EIK Bucket\n-60' EIK Long Reach Boom and Stick\n-60" EIK Ditching bucket\n-Steel Track Pads\n-AUX Hydraulics\n-108k lbs\n\nWE DO NOT NEED TRUCKING SERVICES`,
    attachments: {
      "Number of Buckets": "1",
      "Bucket Width": "60 in",
    },
    categorySpecific: {
      "Auxiliary Hydraulics": "Yes",
      Arm: "Super Long",
      "Arm Length": "60 ft",
      "Reach Type": "Long / Super Long",
      "Boom Length": "60 ft",
    },
    chassis: {
      "Track Type": "Steel",
      Counterweight: "Yes",
      Amphibious: "Yes",
    },
    interior: {
      "A/C": "Yes",
      "A/C Condition": "Excellent",
      Heater: "Yes",
    },
    shipping: {
      "Shipping Weight": "108,000 lb",
    },
    machineLocation: "111 Houston, Texas 77001",
    seller: {
      name: "O'Shea Equipment Company",
      contact: "Shamus O'Shea",
      phone: "(817) 422-1393",
      city: "Montgomery, Texas 77356-3219",
    },
  },
  {
    id: "oshkosh-mk23-2008",
    title: "2008 OSHKOSH MK23",
    category: "Water Truck",
    location: "Houston, Texas",
    hours: 5000,
    priceText: "CALL FOR PRICE",
    images: [
      "/2008Oshkosh1.jpeg",
      "/2008Oshkosh2.jpeg",
      "/2008Oshkosh3.jpeg",
      "/2008Oshkosh4.jpeg",

    ],
    featured: true,
    specs: {
      year: 2008,
      manufacturer: "OSHKOSH",
      model: "MK23",
      serialNumber: "10TDMWE368S104774",
      condition: "Used",
      hours: 5000,
      mileage: "11,405 mi",
      stockNumber: "10TDMWE368S104774",
    },
    description:
      `2008 OshKosh MK23 6x6 4,000 Gallon Water Truck CUSTOM NEW BUILD\n\nVIN 10TDMWE368S104774\n-1,700 Hours on the used military chassis\n-BRAND NEW 4k gallon tank and spray system custom build\n-CAT C12 W Allison Transmission\n-Hydraulic Driven Pump\n-Cab Controlled Spray System\n-3" 500GPM Water cannon with in cab joystick control\n-CAB AC\n-Great tires\n-Front Light bar\n-2 Light bars in the rear\n-Backup camera\n-CUSTOM COLORS AVAILABLE\n\nWE DO NOT NEED TRUCKING SERVICES`,
    capacities: {
      Capacity: "4,000 gal",
    },
    interior: {
      "A/C Condition": "New",
      "A/C": "Yes",
    },
    powertrain: {
      Horsepower: "408 HP",
      Drive: "6WD",
      Engine: "CAT C12",
      "Engine Arrangement": "CAT C12",
    },
    shipping: {
      "Shipping Weight": "32,000 lb",
    },
    machineLocation: "111 Houston, Texas 77001",
    seller: {
      name: "O'Shea Equipment Company",
      contact: "Shamus O'Shea",
      phone: "(817) 422-1393",
      city: "Montgomery, Texas 77356-3219",
    },
  },
  {
    id: "oshkosh-mk23-2003",
    title: "2003 OSHKOSH MK23",
    category: "Water Truck",
    location: "Bryan, Texas",
    hours: 5000,
    priceText: "CALL FOR PRICE",
    images: [
      "/2003Oshkosh1.jpeg",
      "/2003Oshkosh2.jpeg",
      "/2003Oshkosh3.jpeg",
      "/2003Oshkosh4.jpeg",
    ],
    featured: true,
    specs: {
      year: 2003,
      manufacturer: "OSHKOSH",
      model: "MK23",
      serialNumber: "10TDMWE363S07494",
      condition: "Used",
      hours: 5000,
      mileage: "1,000 mi",
      hoursMeter: "Accurate / Verified",
    },
    description:
      `2003 OshKosh MK23 6x6 4,000 Gallon Water Truck CUSTOM NEW BUILD\n\nVIN 10TDMWE363S07494\n-1,700 Hours on the used military chassis\n-BRAND NEW 4k gallon tank and spray system custom build\n-CAT C12 W Allison Transmission\n-Hydraulic Driven Pump\n-Cab Controlled Spray System\n-3" 500GPM Water cannon w in cab joystick controls\n-CAB AC\n-Great tires\n-2 Light bars in the rear\n-CUSTOM COLORS AVAILABLE\n\nWE DO NOT NEED TRUCKING SERVICES`,
    capacities: {
      Capacity: "4,000 gal",
    },
    interior: {
      "A/C Condition": "New",
      "A/C": "Yes",
    },
    powertrain: {
      Horsepower: "408 HP",
      Drive: "6WD",
      Engine: "CAT C12",
      "Engine Arrangement": "CAT C12",
    },
    machineLocation: "111 Bryan, Texas 77801",
    seller: {
      name: "O'Shea Equipment Company",
      contact: "Shamus O'Shea",
      phone: "(817) 422-1393",
      city: "Montgomery, Texas 77356-3219",
    },
  },
  {
    id: "oshkosh-mk23-2003b",
    title: "2003 OSHKOSH MK23",
    category: "Water Truck",
    location: "Houston, Texas",
    hours: 1782,
    priceText: "CALL FOR PRICE",
    images: [
      "/2003OshkoshWhite1.jpeg",
      "/2003OshkoshWhite2.jpeg",
      "/2003OshkoshWhite3.jpeg",
      "/2003OshkoshWhite4.jpeg",
      "/2003OshkoshWhite5.jpeg",
      "/2003OshkoshWhite6.jpeg",
      "/2003OshkoshWhite7.jpeg",
      "/2003OshkoshWhite8.jpeg",
      "/2003OshkoshWhite9.jpeg",
      "/2003OshkoshWhite10.jpeg",
      "/2003OshkoshWhite11.jpeg",
      "/2003OshkoshWhite12.jpeg",
      "/2003OshkoshWhite13.jpeg",
      "/2003OshkoshWhite14.jpeg",
      "/2003OshkoshWhite15.jpeg",
    ],
    featured: true,
    specs: {
      year: 2003,
      manufacturer: "OSHKOSH",
      model: "MK23",
      serialNumber: "10TDMWE363S074944",
      condition: "Used",
      hours: 1782,
    },
    description:
      `2003 OshKosh MK23 6x6 4,000 Gallon Water Truck\n\nVIN 10TDMWE363S074944\n-1,782 Hours\n-Less than 40 hours on new 4k gallon tank and spray system\n-CAT C12 W Allison Transmission\n-Hydraulic Driven Pump\n-Cab Controlled Spray System\n-CAB AC\n-Great tires\n-2 Light bars in the rear\n\nWE DO NOT NEED TRUCKING SERVICES`,
    capacities: {
      Capacity: "4,000 gal",
    },
    interior: {
      "A/C Condition": "Excellent",
      "A/C": "Yes",
    },
    powertrain: {
      Horsepower: "408 HP",
      Engine: "C12",
      "Engine Arrangement": "C12",
    },
    machineLocation: "111 Houston, Texas 77001",
    seller: {
      name: "O'Shea Equipment Company",
      contact: "Shamus O'Shea",
      phone: "(817) 422-1393",
      city: "Montgomery, Texas 77356-3219",
    },
  },
  {
    id: "oshkosh-mk23-2002",
    title: "2002 OSHKOSH MK23",
    category: "Water Truck",
    location: "Houston, Texas",
    hours: 2896,
    priceText: "CALL FOR PRICE",
    images: [
      "/2002OshkoshWhite1.jpeg",
      "/2002OshkoshWhite2.jpeg",
      "/2002OshkoshWhite3.jpeg",
      "/2002OshkoshWhite4.jpeg",
      "/2002OshkoshWhite5.jpeg",
      "/2002OshkoshWhite6.webp",
      "/2002OshkoshWhite7.webp",
      "/2002OshkoshWhite8.webp",
      "/2002OshkoshWhite9.jpeg",
      "/2002OshkoshWhite10.jpeg",
      "/2002OshkoshWhite11.jpeg",
      "/2002OshkoshWhite12.jpeg",
      "/2002OshkoshWhite13.jpeg"
    ],
    featured: true,
    specs: {
      year: 2002,
      manufacturer: "OSHKOSH",
      model: "MK23",
      serialNumber: "10TDWE362S073713",
      condition: "Used",
      hours: 2896,
    },
    description:
      `2002 OshKosh MK23 6x6 4,000 Gallon Water Truck\n\nVIN 10TDWE362S073713\n-2,896 Hours\n-Less than 20 hours on new 4k gallon tank and spray system\n-CAT C12 W Allison Transmission\n-Hydraulic Driven Pump\n-Cab Controlled Spray System\n-CAB AC\n-Upgraded Doors and handles\n-Great tires\n-2 Light bars in the rear\n\nWE DO NOT NEED TRUCKING SERVICES`,
    interior: {
      "A/C Condition": "Excellent",
      "A/C": "Yes",
    },
    powertrain: {
      Drive: "6WD",
      Engine: "CAT C12",
      "Engine Arrangement": "CAT C12",
    },
    machineLocation: "111 Houston, Texas 77001",
    seller: {
      name: "O'Shea Equipment Company",
      contact: "Shamus O'Shea",
      phone: "(817) 422-1393",
      city: "Montgomery, Texas 77356-3219",
    },
  },
];

export function getListingById(id) {
  return listings.find((l) => l.id === id);
}


